# Generated by Django 5.0.3 on 2024-03-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
