# Generated by Django 5.0.3 on 2024-03-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0004_remove_chat_receiver_chat_sender2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender2',
            new_name='receiver',
        ),
    ]
