# Generated by Django 5.0.3 on 2024-04-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0007_yoga_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
