# Generated by Django 5.0.3 on 2024-04-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0010_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='logo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='logo',
            new_name='image',
        ),
    ]
