# Generated by Django 5.0.3 on 2024-04-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0011_rename_logo_doctor_image_rename_logo_trainer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('report', models.FileField(null=True, upload_to='')),
                ('prescription', models.FileField(max_length=200, null=True, upload_to='')),
                ('testStatus', models.IntegerField(default=0)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.doctor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.customer')),
            ],
        ),
    ]
