# Generated by Django 5.0.3 on 2024-05-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0012_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromm', models.DateField()),
                ('to', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('online_or_offline', models.CharField(max_length=20)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.trainer')),
            ],
        ),
    ]
