# Generated by Django 5.0.3 on 2024-05-02 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0013_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.classes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.customer')),
            ],
        ),
    ]
